### ISSUE TITLE
Data analysis repo in Python

### ISSUE THREAD

**Issue by diegoquintanav** [danilofreire/pinochet-regime-data#2]
Hello! first of all, thanks for this. 

I started a repo in https://github.com/diegoquintanav/pinochet-analyze/ with the intention of working on the dataset and put my results there. 

I will be using mostly Python, and at the moment I have a prototype of an interactive map in a jupyter notebook in <https://nbviewer.jupyter.org/github/diegoquintanav/pinochet-analyze/blob/master/prototypes/maps/pinochet-maps.ipynb> (The notebook is in spanish, a decision I'm not sure about) which I will be updating. I'll be also adding analysis ideas in the `issues` tab. Please let me know of any concerns, ideas and thoughts you have about this.

Thank you again

**Comment by danilofreire** [comment]
Hi Diego!

Thanks very much for your message. I'm very happy that you like the package and have decided to add an interactive map with the data we have. I feel very flattered, it looks great. I'm happy to chat about data visualisation and think about how we can present the dataset to users who are not familiar with the information it contains. If I can help you in any way, please let me know! Thanks again!

**Comment by diegoquintanav** [comment]
Hey I am again onto this, I modeled the dataset as a property graph with neo4j, and you can query the data differently:

The graph "schema" I'm using is roughly like this

![image](https://user-images.githubusercontent.com/16281387/88490323-296b4d80-cf9b-11ea-84b8-84519c09b458.png)

and you can query for instance, the full trajectory a person did until it ended in a event (which I named `ViolentEvent`)

![image](https://user-images.githubusercontent.com/16281387/88490301-017bea00-cf9b-11ea-8b53-02f0549b613b.png)

My next goal is to serve this graph through a graphQL implementation, and integrate it with other data related, on graphQL and perhaps a semantic layer ontop. I'm trying stuff I learnt in the past semester :tada:

**Comment by danilofreire** [comment]
Hi Diego!

Thanks for posting your new project here! I think it's a great idea and I really like your implementation. Is it online yet? I'll surely recommend it to my friends and colleagues. Please share your code too, the graphs look great! Thanks a lot! :D

**Comment by diegoquintanav** [comment]
The repo is the same as before, https://github.com/diegoquintanav/pinochet-analyze/

it uses docker and docker-compose, so it's not online yet... but you can try it by yourself doing `docker-compose up -d` and then `python services/graph-api/manage.py recreate_db`, and you should have access to the interface locally at `http://0.0.0.0:7474/browser/`

**Comment by danilofreire** [comment]
Thanks very much, Diego! I will take a closer look into your repository, it
seems very interesting!
