### ISSUE TITLE
meaning of columns start_location_1 and end_location_n, etc

### ISSUE THREAD

**Issue by diegoquintanav** [danilofreire/pinochet-regime-data#3]
I noticed that the csv header has some undocumented attributes

- start_location_1
- location_2
- end_location_3
- end_location_4
- end_location_5
- end_location_6

what's the reasoning behind these names? I mean, why not an end_location_2 then? are these meant to be treated as location_n as per the appendix?

**Comment by danilofreire** [comment]
Hi Diego,

Thanks for pointing that out. I've just updated the column names to reflect what's in the appendix. Yes, they should all be treated as `location_n`. The `.csv`, `.RData`, and `.xlsx` files have been corrected and I'm uploading the package version to CRAN. Thanks again!

**Comment by diegoquintanav** [comment]
great! thank you. For future reference, 48e942473 closes this.
